# Install Node version 20
FROM node:20

# Example; install htop by default
RUN apt update -y && apt install -y htop

# Install Ionic CLI and TypeScript compiler
RUN npm install -g @ionic/cli typescript
